service: cvs-tsk-update-status

provider:
  name: aws
  runtime: nodejs14.x
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:region:XXXXXX:cert-gen-q
          batchSize: 10
